name: Docker Image CI
on:
  push:
    branches: [ "main" ]
    paths:
      - "**/Dockerfile"
  schedule:
    - cron: '15 7 * * *'
  workflow_dispatch:
env:
  IMAGE_NAME: zkoesters/mhserveremu
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 'nightly'
            path: 'nightly'
          - version: 'nightly-alpine'
            path: 'nightly/alpine'
          - version: 'testing'
            path: 'testing'
          - version: 'testing-alpine'
            path: 'testing/alpine'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up rclone
        uses: AnimMouse/setup-rclone@e4c62ff5f942e489edceaffb563832d970253322 # v1.10.1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: Download necessary files
        run: |
          rclone copy r2:private-dependencies/Calligraphy.sip ${{ github.workspace }}
          rclone copy r2:private-dependencies/mu_cdata.sip ${{ github.workspace }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # v6.12.0
        with:
          context: .
          file: ${{ matrix.path }}/Dockerfile
          platforms: linux/amd64
          annotations: ${{ steps.meta.outputs.annotations }}
          sbom: true
          provenance: mode=max
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.version }}